export { default as Header } from './components/Header'
export { default as Hero} from './components/Hero'
export { default as AboutMe } from './components/AboutMe'
export { default as ContactMe } from './components/ContactMe'
export { default as Projects } from './components/Projects'